package com.careydevelopment.contact.config;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;

import com.careydevelopment.contact.model.Contact;
import com.careydevelopment.contact.repository.AccountRepository;
import com.careydevelopment.contact.repository.ContactRepository;
import com.careydevelopment.contact.service.ContactService;
import com.careydevelopment.contact.service.ServiceException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.TypeFactory;

@Component
public class ApplicationListenerInitialize implements ApplicationListener<ApplicationReadyEvent>  {
    
    @Autowired
    private ContactService contactService;
    
    @Autowired
    private AccountRepository accountRepository;
    
    @Autowired
    private ContactRepository contactRepository;
    
    private String data = "[ {\r\n"
            + "  \"id\" : \"5fde12d60ab013769b67cf02\",\r\n"
            + "  \"firstName\" : \"Chew\",\r\n"
            + "  \"lastName\" : \"Bacca\",\r\n"
            + "  \"email\" : \"chewie@xmail.com\",\r\n"
            + "  \"source\" : \"WEBSITE_FORM\",\r\n"
            + "  \"status\" : \"ACTIVE\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"ANGULAR\" ],\r\n"
            + "  \"title\" : \"Wookie\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"sales\" : [ {\r\n"
            + "    \"purchaseOrderNumber\" : \"09393\",\r\n"
            + "    \"title\" : \"Angular UI Refactoring\",\r\n"
            + "    \"value\" : 100000,\r\n"
            + "    \"date\" : 1609650000000,\r\n"
            + "    \"lineOfBusiness\" : \"ANGULAR\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09394\",\r\n"
            + "    \"title\" : \"Revamp CRM UI\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1610254800000,\r\n"
            + "    \"lineOfBusiness\" : \"ANGULAR\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09395\",\r\n"
            + "    \"title\" : \"Angular tutorial\",\r\n"
            + "    \"value\" : 20000,\r\n"
            + "    \"date\" : 1610427600000,\r\n"
            + "    \"lineOfBusiness\" : \"ANGULAR\"\r\n"
            + "  }],\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"Working for Han\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"117 Fortunata Way\",\r\n"
            + "        \"city\": \"Memphis\",\r\n"
            + "        \"state\": \"TN\",\r\n"
            + "        \"zip\": \"27002\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"REAL_ESTATE\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fde1028792009283c603929\",\r\n"
            + "  \"firstName\" : \"JarJar\",\r\n"
            + "  \"lastName\" : \"Binks\",\r\n"
            + "  \"email\" : \"jarjar@xmail.com\",\r\n"
            + "  \"addresses\" : [ {\r\n"
            + "    \"street1\" : \"1400 Plum Way\",\r\n"
            + "    \"city\" : \"Onisius\",\r\n"
            + "    \"state\" : \"NM\",\r\n"
            + "    \"zip\" : \"80909\",\r\n"
            + "    \"addressType\" : \"HOME\"\r\n"
            + "  } ],\r\n"
            + "  \"source\" : \"WALKIN\",\r\n"
            + "  \"status\" : \"CONTACTED\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"FULL_STACK\" ],\r\n"
            + "  \"title\" : \"Comic Relief\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"sales\" : [ {\r\n"
            + "    \"purchaseOrderNumber\" : \"09396\",\r\n"
            + "    \"title\" : \"Spring Boot API for In-House REST Service\",\r\n"
            + "    \"value\" : 310000,\r\n"
            + "    \"date\" : 1609736400000\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09396\",\r\n"
            + "    \"title\" : \"Angular Optimization\",\r\n"
            + "    \"value\" : 200000,\r\n"
            + "    \"date\" : 1610859600000,\r\n"
            + "    \"lineOfBusiness\" : \"ANGULAR\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09397\",\r\n"
            + "    \"title\" : \"Full Stack Work\",\r\n"
            + "    \"value\" : 110000,\r\n"
            + "    \"date\" : 1610946000000,\r\n"
            + "    \"lineOfBusiness\" : \"FULL_STACK\"\r\n"
            + "  } ],\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"Queen Inc.\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"122 Elio St.\",\r\n"
            + "        \"city\": \"St. Paul\",\r\n"
            + "        \"state\": \"MN\",\r\n"
            + "        \"zip\": \"57102\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"FINANCE\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fde117edd79e20e3ff6528c\",\r\n"
            + "  \"firstName\" : \"Lando\",\r\n"
            + "  \"lastName\" : \"Calrissian\",\r\n"
            + "  \"email\" : \"lando@xmail.com\",\r\n"
            + "  \"phones\" : [ {\r\n"
            + "    \"phone\" : \"(555) 555-5555\",\r\n"
            + "    \"phoneType\" : \"WORK\",\r\n"
            + "    \"countryCode\" : \"us\"\r\n"
            + "  } ],\r\n"
            + "  \"source\" : \"INBOUND_SALES_CALL\",\r\n"
            + "  \"status\" : \"CONTACTED\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"ANGULAR\", \"DEV_OPS\" ],\r\n"
            + "  \"title\" : \"Friend\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"sales\" : [ {\r\n"
            + "    \"purchaseOrderNumber\" : \"09398\",\r\n"
            + "    \"title\" : \"Harness Training\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1610082000000,\r\n"
            + "    \"lineOfBusiness\" : \"DEV_OPS\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09399\",\r\n"
            + "    \"title\" : \"Jenkins Training\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1610254800000,\r\n"
            + "    \"lineOfBusiness\" : \"DEV_OPS\"\r\n"
            + "  } ],\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"Cloud City\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"1 Cloud Plaza\",\r\n"
            + "        \"city\": \"Phoenix\",\r\n"
            + "        \"state\": \"AZ\",\r\n"
            + "        \"zip\": \"98030\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"MINING\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fde1ac084dad94dbb7f82ae\",\r\n"
            + "  \"firstName\" : \"R2D2\",\r\n"
            + "  \"lastName\" : \"Droid\",\r\n"
            + "  \"email\" : \"r2d2@xmail.com\",\r\n"
            + "  \"source\" : \"EMAIL\",\r\n"
            + "  \"status\" : \"ACTIVE\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"JAVA_ENTERPRISE\" ],\r\n"
            + "  \"title\" : \"Droid\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"For Luke\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"222 Tatt\",\r\n"
            + "        \"city\": \"Seattle\",\r\n"
            + "        \"state\": \"WA\",\r\n"
            + "        \"zip\": \"98020\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"OTHER\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fdd0af34e9d6806f369abf0\",\r\n"
            + "  \"firstName\" : \"Boba\",\r\n"
            + "  \"lastName\" : \"Fett\",\r\n"
            + "  \"email\" : \"boba@xmail.com\",\r\n"
            + "  \"phones\" : [ {\r\n"
            + "    \"phone\" : \"(555) 555-5555\",\r\n"
            + "    \"phoneType\" : \"HOME\",\r\n"
            + "    \"countryCode\" : \"us\"\r\n"
            + "  } ],\r\n"
            + "  \"addresses\" : [ {\r\n"
            + "    \"street1\" : \"1222 Galaxy Way\",\r\n"
            + "    \"city\" : \"Alterion\",\r\n"
            + "    \"state\" : \"AR\",\r\n"
            + "    \"zip\" : \"22222\",\r\n"
            + "    \"country\" : \"US\",\r\n"
            + "    \"addressType\" : \"HOME\"\r\n"
            + "  } ],\r\n"
            + "  \"source\" : \"INBOUND_SALES_CALL\",\r\n"
            + "  \"status\" : \"CONTACTED\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"DEV_OPS\" ],\r\n"
            + "  \"title\" : \"Bounty Hunter\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"sales\" : [ {\r\n"
            + "    \"purchaseOrderNumber\" : \"09400\",\r\n"
            + "    \"title\" : \"Jenkins Training\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1610341200000,\r\n"
            + "    \"lineOfBusiness\" : \"DEV_OPS\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09401\",\r\n"
            + "    \"title\" : \"Kubernetes Training\",\r\n"
            + "    \"value\" : 200000,\r\n"
            + "    \"date\" : 1610686800000,\r\n"
            + "    \"lineOfBusiness\" : \"DEV_OPS\"\r\n"
            + "  } ],\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"Empire\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"88 Eights\",\r\n"
            + "        \"city\": \"Boston\",\r\n"
            + "        \"state\": \"MA\",\r\n"
            + "        \"zip\": \"02020\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"AGRICULTURE\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fdd0cedaac5f75d62564ee7\",\r\n"
            + "  \"firstName\" : \"Jabba\",\r\n"
            + "  \"lastName\" : \"Hutt\",\r\n"
            + "  \"email\" : \"jabba@xmail.com\",\r\n"
            + "  \"source\" : \"EMAIL\",\r\n"
            + "  \"status\" : \"NEW\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"ANGULAR\" ],\r\n"
            + "  \"title\" : \"Large\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"sales\" : [ {\r\n"
            + "    \"purchaseOrderNumber\" : \"09403\",\r\n"
            + "    \"title\" : \"Update UI to Match Wireframes\",\r\n"
            + "    \"value\" : 200000,\r\n"
            + "    \"date\" : 1609822800000,\r\n"
            + "    \"lineOfBusiness\" : \"ANGULAR\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09403\",\r\n"
            + "    \"title\" : \"Improve UI Responsiveness\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1610254800000,\r\n"
            + "    \"lineOfBusiness\" : \"ANGULAR\"\r\n"
            + "  } ],\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"Sandz\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"188 Blunio Way\",\r\n"
            + "        \"city\": \"Memphis\",\r\n"
            + "        \"state\": \"TN\",\r\n"
            + "        \"zip\": \"27002\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"MATERIALS\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fdd0e7c870ef4713e179384\",\r\n"
            + "  \"firstName\" : \"Princess\",\r\n"
            + "  \"lastName\" : \"Leia\",\r\n"
            + "  \"email\" : \"leia@xmail.com\",\r\n"
            + "  \"phones\" : [ {\r\n"
            + "    \"phone\" : \"(555) 555-5555\",\r\n"
            + "    \"phoneType\" : \"WORK\",\r\n"
            + "    \"countryCode\" : \"us\"\r\n"
            + "  } ],\r\n"
            + "  \"source\" : \"WALKIN\",\r\n"
            + "  \"status\" : \"INTERESTED\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"JAVA_ENTERPRISE\", \"ANGULAR\" ],\r\n"
            + "  \"title\" : \"Princess\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"sales\" : [ {\r\n"
            + "    \"purchaseOrderNumber\" : \"09404\",\r\n"
            + "    \"title\" : \"Upgrade Spring Boot application to Java 11\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1610341200000,\r\n"
            + "    \"lineOfBusiness\" : \"JAVA_ENTERPRISE\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09406\",\r\n"
            + "    \"title\" : \"Improve Exception Handling in Spring Boot application\",\r\n"
            + "    \"value\" : 250000,\r\n"
            + "    \"date\" : 1610600400000,\r\n"
            + "    \"lineOfBusiness\" : \"JAVA_ENTERPRISE\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09407\",\r\n"
            + "    \"title\" : \"Support Additional External REST services in Spring Boot\",\r\n"
            + "    \"value\" : 350000,\r\n"
            + "    \"date\" : 1611118800000,\r\n"
            + "    \"lineOfBusiness\" : \"JAVA_ENTERPRISE\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09408\",\r\n"
            + "    \"title\" : \"Enhance UI for Accounting App\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1611205200000,\r\n"
            + "    \"lineOfBusiness\" : \"ANGULAR\"\r\n"
            + "  } ],\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"Republic\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"77 Your Worship\",\r\n"
            + "        \"city\": \"Chicago\",\r\n"
            + "        \"state\": \"IL\",\r\n"
            + "        \"zip\": \"60606\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"CONSTRUCTION\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fd5f37bde602d3bacef69db\",\r\n"
            + "  \"firstName\" : \"Luke\",\r\n"
            + "  \"lastName\" : \"Skywalker\",\r\n"
            + "  \"email\" : \"luke@tat2.com\",\r\n"
            + "  \"source\" : \"EMAIL\",\r\n"
            + "  \"sourceDetails\" : \"He emailed me\",\r\n"
            + "  \"status\" : \"NEW\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"linesOfBusiness\" : [ \"ANGULAR\" ],\r\n"
            + "  \"title\" : \"President\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"International Business\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"33 White St.\",\r\n"
            + "        \"city\": \"White Plains\",\r\n"
            + "        \"state\": \"NY\",\r\n"
            + "        \"zip\": \"22002\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"DATA_PROCESSING\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"5fdd0f2aea599836ca3ddbf1\",\r\n"
            + "  \"firstName\" : \"Han\",\r\n"
            + "  \"lastName\" : \"Solo\",\r\n"
            + "  \"email\" : \"han@xmail.com\",\r\n"
            + "  \"addresses\" : [ {\r\n"
            + "    \"street1\" : \"111 Millennium Way\",\r\n"
            + "    \"city\" : \"Nessy\",\r\n"
            + "    \"state\" : \"CO\",\r\n"
            + "    \"addressType\" : \"HOME\"\r\n"
            + "  } ],\r\n"
            + "  \"source\" : \"EMAIL\",\r\n"
            + "  \"status\" : \"ACTIVE\",\r\n"
            + "  \"statusChange\" : 0,\r\n"
            + "  \"title\" : \"Pirate\",\r\n"
            + "  \"authority\" : false,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"5f78d8fbc1d3246ab4303f2b\",\r\n"
            + "    \"firstName\" : \"Darth\",\r\n"
            + "    \"lastName\" : \"Vader\",\r\n"
            + "    \"email\" : \"darth@xmail.com\",\r\n"
            + "    \"username\" : \"darth\",\r\n"
            + "    \"phoneNumber\" : \"474-555-1212\"\r\n"
            + "  },  \"account\" : {\r\n"
            + "    \"name\" : \"Working for Han\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"117 Fortunata Way\",\r\n"
            + "        \"city\": \"Memphis\",\r\n"
            + "        \"state\": \"TN\",\r\n"
            + "        \"zip\": \"27002\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"REAL_ESTATE\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "}, {\r\n"
            + "  \"id\" : \"6005e87163660b7b2e6a16df\",\r\n"
            + "  \"firstName\" : \"Governor\",\r\n"
            + "  \"lastName\" : \"Tarkin\",\r\n"
            + "  \"email\" : \"tarkin@xmail.com\",\r\n"
            + "  \"phones\" : [ {\r\n"
            + "    \"phone\" : \"(555) 555-5555\",\r\n"
            + "    \"phoneType\" : \"CELL\"\r\n"
            + "  } ],\r\n"
            + "  \"addresses\" : [ {\r\n"
            + "    \"city\" : \"Home City\",\r\n"
            + "    \"state\" : \"MN\",\r\n"
            + "    \"addressType\" : \"HOME\"\r\n"
            + "  } ],\r\n"
            + "  \"source\" : \"EMAIL\",\r\n"
            + "  \"status\" : \"ACTIVE\",\r\n"
            + "  \"linesOfBusiness\" : [ \"FULL_STACK\" ],\r\n"
            + "  \"title\" : \"Governor\",\r\n"
            + "  \"authority\" : true,\r\n"
            + "  \"salesOwner\" : {\r\n"
            + "    \"id\" : \"6005e76bac127e0f5d9a6560\",\r\n"
            + "    \"firstName\" : \"The\",\r\n"
            + "    \"lastName\" : \"Emperor\",\r\n"
            + "    \"email\" : \"theemperor@xmail.com\",\r\n"
            + "    \"username\" : \"theemperor\",\r\n"
            + "    \"phoneNumber\" : \"(555) 555-5555\"\r\n"
            + "  },\r\n"
            + "  \"sales\" : [ {\r\n"
            + "    \"purchaseOrderNumber\" : \"09409\",\r\n"
            + "    \"title\" : \"Refactor Spring Boot application\",\r\n"
            + "    \"value\" : 150000,\r\n"
            + "    \"date\" : 1610341200000,\r\n"
            + "    \"lineOfBusiness\" : \"JAVA_ENTERPRISE\"\r\n"
            + "  }, {\r\n"
            + "    \"purchaseOrderNumber\" : \"09410\",\r\n"
            + "    \"title\" : \"Full stack refactoring\",\r\n"
            + "    \"value\" : 250000,\r\n"
            + "    \"date\" : 1610600400000,\r\n"
            + "    \"lineOfBusiness\" : \"FULL_STACK\"\r\n"
            + "  } ],\r\n"
            + "  \"account\" : {\r\n"
            + "    \"name\" : \"No Moon\",\r\n"
            + "    \"address\" : {\r\n"
            + "        \"street1\": \"55 Space Station St.\",\r\n"
            + "        \"city\": \"Memphis\",\r\n"
            + "        \"state\": \"TN\",\r\n"
            + "        \"zip\": \"27002\"\r\n"
            + "    },\r\n"
            + "    \"industry\": \"OTHER\",\r\n"
            + "    \"phone\" : {\r\n"
            + "        \"countryCode\": \"1\",\r\n"
            + "        \"phone\": \"(555) 555-5555\"\r\n"
            + "    }\r\n"
            + "  } \r\n"
            + "} ]";
    
    public void onApplicationEvent(ApplicationReadyEvent event) {
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            TypeFactory typeFactory = objectMapper.getTypeFactory();
            List<Contact> list = (List<Contact>)objectMapper.readValue(data, typeFactory.constructCollectionType(List.class, Contact.class));
            //System.err.println(list);
            for (Contact contact : list) {
                this.contactRepository.save(contact);
            }
        } catch (ServiceException e) {
            System.err.println(e.getMessage() + " " + e.getStatusCode());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}