package com.careydevelopment.customer.model;

public enum Industry {

    HOSPITALITY,
    HEALTHCARE,
    ADMINISTRATIVE_SUPPORT,
    AGRICULTURE,
    TRANSPORTATION,
    AMUSEMENT,
    ARTS,
    APPAREL,
    BEVERAGE,
    BROADCASTING,
    MATERIALS,
    CHEMICAL_MANUFACTURING,
    RETAIL,
    ELECTRONICS,
    CONSTRUCTION,
    REAL_ESTATE,
    FINANCE,
    DATA_PROCESSING,
    EDUCATION,
    INSURANCE,
    FURNITURE,
    MINING,
    ENERGY,
    PUBLIC_SECTOR,
    OTHER
}
